# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "772a0afac39a2708a316fca21f60fa3d"
name = "post-purchase-upsellify"
handle = "post-purchase-upsellify"
application_url = "https://french-picks-colleague-norwegian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dailey-project.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://french-picks-colleague-norwegian.trycloudflare.com/auth/callback",
  "https://french-picks-colleague-norwegian.trycloudflare.com/auth/shopify/callback",
  "https://french-picks-colleague-norwegian.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
